root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -ldflags='-s -w' -o ./tmp/main cmd/server/main.go"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docker", "bin", "data", ".git", "node_modules", "docs"]
  exclude_file = ["*.md", "*.txt", "*.log", "*.sql", "docker-compose*.yml", "Dockerfile*"]
  exclude_regex = ["_test\\.go$", "\\.git.*", ".*\\.swp$", ".*\\.tmp$"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal", "configs"]
  include_ext = ["go", "yaml", "yml", "json"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 300
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = false
