image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Mage
    init: |
      go install github.com/magefile/mage@latest
      export PATH=$PATH:$(go env GOPATH)/bin
    command: echo 'Mage installed, ready for dev.'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 8080 for the frontend
    port: 8080
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
