services:
  database:
    image: postgres:15-alpine
    container_name: controlme-database
    environment:
      POSTGRES_DB: controlme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - controlme-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d controlme"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncomment when ready to containerize the Go application
  server:
    image: cosmtrek/air
    container_name: controlme-server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - CONFIG_FILE=config.docker.yaml  # Use Docker-specific config
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=controlme
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - controlme-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  controlme-network:
    driver: bridge
