# ControlMe Go Backend Configuration
# Copy this file to config.yaml and modify the values as needed

# Application environment: development, staging, production
environment: development

# Server configuration
server:
  port: 8080
  host: localhost
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

# Database configuration (PostgreSQL)
database:
  host: localhost
  port: 5432
  name: controlme
  username: postgres
  password: postgres
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

# Redis configuration (for caching and WebSocket scaling)
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  dial_timeout: 5s

# Authentication configuration
auth:
  # JWT secret for modern API authentication
  jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
  jwt_expiration: 86400  # 24 hours in seconds
  jwt_refresh_expiration: 604800  # 7 days in seconds
  
  # Legacy crypto settings for .NET client compatibility
  legacy_crypto_key: "your-legacy-crypto-key-from-csharp-app"
  legacy_iv: "your-legacy-iv-from-csharp-app"

# Legacy compatibility settings
legacy:
  # Enable upgrade notifications for legacy clients
  upgrade_notifications: true
  notification_frequency: 24  # hours between notifications
  sunset_date: "2025-10-01"  # Date when legacy support will be removed
  
  # Legacy response format compatibility
  strict_response_format: true
  preserve_original_errors: true

# WebSocket configuration
websocket:
  # Maximum number of concurrent connections
  max_connections: 1000
  
  # Message buffer sizes
  read_buffer_size: 1024
  write_buffer_size: 1024
  
  # Timeouts
  write_wait: 10s
  pong_wait: 60s
  ping_period: 54s
  
  # Maximum message size
  max_message_size: 512

# CORS configuration
cors:
  enabled: true
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 3600

# Rate limiting
rate_limit:
  enabled: true
  requests_per_minute: 100
  burst: 20

# Logging configuration
logging:
  level: info  # debug, info, warn, error
  format: json  # json, text
  output: stdout  # stdout, file
  file_path: logs/controlme.log
  max_size: 100  # MB
  max_backups: 5
  max_age: 30  # days

# Security headers
security:
  enable_hsts: true
  enable_content_type_nosniff: true
  enable_frame_deny: true
  enable_xss_protection: true

# Monitoring and metrics
monitoring:
  enabled: false
  metrics_path: /metrics
  health_path: /health
